/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.32
 * Generated at: 2023-06-26 07:22:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.view;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import bean.User;
import bean.User;

public final class menu_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/common/userinfo.jsp", Long.valueOf(1687738818706L));
    _jspx_dependants.put("/common/header.jsp", Long.valueOf(1687495315964L));
    _jspx_dependants.put("/common/footer.jsp", Long.valueOf(1687495309217L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("bean.User");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

User user = (User)session.getAttribute("user");

//セッション切れか確認
if(user == null){
	request.setAttribute("error", "セッション切れの為、メニュー画面が表示できませんでした。");
	request.setAttribute("cmd", "logout");
	request.getRequestDispatcher("/view/error.jsp").forward(request, response);
	return;
}

      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<title>メニュー画面</title>\r\n");
      out.write("\t</head>\r\n");
      out.write("\t<body>\r\n");
      out.write("\t\t<div style=\"text-align:center\">\r\n");
      out.write("\t\t\t<!-- ヘッダー -->\r\n");
      out.write("\t\t\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<header style=\"text-align:center\">\r\n");
      out.write("\t<h1 style=\"color:#32CD32\">ユニフォーム受注管理システム</h1>\r\n");
      out.write("\t<hr style=\"height:9; background-color:#32CD32\"/>\r\n");
      out.write("</header>");
      out.write("\r\n");
      out.write("\t\t\t<!-- ユーザー情報 -->\r\n");
      out.write("\t\t\t<table style=\"margin-left:auto\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>名前：");
      out.print(user.getName() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>権限：\r\n");
      out.write("\t\t\t\t\t\t");
if(user.getAuthority().equals("1")){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t管理者\r\n");
      out.write("\t\t\t\t\t\t");
}else if(user.getAuthority().equals("2")){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\tゲスト\r\n");
      out.write("\t\t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t<hr style=\"height:5; background-color:#32CD32\"/>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<h2 style=\"color:#A52A2A\">MENU</h2>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<hr style=\"height:5; background-color:#32CD32\"/>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- メニュー一覧 -->\r\n");
      out.write("\t\t\t<!-- 管理者 -->\r\n");
      out.write("\t\t\t");
if(user.getAuthority().equals("1")){ 
      out.write("\r\n");
      out.write("\t\t\t\t<table style=\"align:center; margin:auto; border-spacing:20px\">\r\n");
      out.write("\t\t\t\t\t<tr><td><a href=\"");
      out.print(request.getContextPath() );
      out.write("/list\">[受注一覧]</a></td></tr>\r\n");
      out.write("\t\t\t\t\t<tr><td><a href=\"");
      out.print(request.getContextPath() );
      out.write("/uniformList\">[商品一覧]</a></td></tr>\r\n");
      out.write("\t\t\t\t\t<tr><td><a href=\"");
      out.print(request.getContextPath() );
      out.write("/logout\">[ログアウト]</a></td></tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t");
} 
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- ゲスト -->\r\n");
      out.write("\t\t\t");
if(user.getAuthority().equals("2")){ 
      out.write("\r\n");
      out.write("\t\t\t\t<table style=\"align:center; margin:auto; border-spacing:20px\">\r\n");
      out.write("\t\t\t\t\t<tr><td><a href=\"");
      out.print(request.getContextPath() );
      out.write("/uniformList\">[商品一覧]</a></td></tr>\r\n");
      out.write("\t\t\t\t\t<tr><td><a href=\"");
      out.print(request.getContextPath() );
      out.write("/showCart\">[カート確認]</a></td></tr>\r\n");
      out.write("\t\t\t\t\t<tr><td><a href=\"");
      out.print(request.getContextPath() );
      out.write("/logout\">[ログアウト]</a></td></tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t");
} 
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- フッター -->\r\n");
      out.write("\t\t\t");
      out.write("<footer style=\"text-align:left; position:absolute; bottom:100; width:100%\">\r\n");
      out.write("\t<hr style=\"height:3; background-color:#32CD32\"/>\r\n");
      out.write("\t<p style=\"font-color:#00FF00\">Copyright(C)2023 All Right Reserved</p>\r\n");
      out.write("</footer>");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
