/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.32
 * Generated at: 2023-06-26 02:38:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.view;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import bean.*;

public final class orderList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/common/header.jsp", Long.valueOf(1687495315964L));
    _jspx_dependants.put("/common/footer.jsp", Long.valueOf(1687495309217L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("bean");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	ArrayList<OrderStatus> list = (ArrayList<OrderStatus>)request.getAttribute("order_list");


      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<title>受注状況一覧画面</title>\r\n");
      out.write("\t</head>\r\n");
      out.write("\t<body>\r\n");
      out.write("\t\t<div style=\"text-align:center\">\r\n");
      out.write("\t\t<!-- ヘッダー -->\r\n");
      out.write("\t\t\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<header style=\"text-align:center\">\r\n");
      out.write("\t<h1 style=\"color:#32CD32\">ユニフォーム受注管理システム</h1>\r\n");
      out.write("\t<hr style=\"height:9; background-color:#32CD32\"/>\r\n");
      out.write("</header>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- メニュー -->\r\n");
      out.write("\t\t\t<table style=\"margin:auto; width:100%; align:center\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td style=\"width:30%; text-align:center\">\r\n");
      out.write("\t\t\t\t\t\t[<a href=\"");
      out.print(request.getContextPath() );
      out.write("/view/menu.jsp\">メニューへ戻る</a>]\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"width:30%; font-size:24px; text-align:center; color:#A52A2A\">受注状況一覧</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"width:30%; text-align:center\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<hr style=\"height:1; background-color:#32CD32\"/>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- 一覧表示 -->\r\n");
      out.write("\t\t\t<table style=\"margin:0 auto; width:100%\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th style=\"background-color:#D3D3D3; width:14%\">No</th>\r\n");
      out.write("\t\t\t\t\t<th style=\"background-color:#D3D3D3; width:14%\">氏名</th>\r\n");
      out.write("\t\t\t\t\t<th style=\"background-color:#D3D3D3; width:14%\">合計金額</th>\r\n");
      out.write("\t\t\t\t\t<th style=\"background-color:#D3D3D3; width:14%\">発注日</th>\r\n");
      out.write("\t\t\t\t\t<th style=\"background-color:#D3D3D3; width:14%\">入金状況</th>\r\n");
      out.write("\t\t\t\t\t<th style=\"background-color:#D3D3D3; width:14%\">発送準備</th>\r\n");
      out.write("\t\t\t\t\t<th style=\"background-color:#D3D3D3; width:14%\">&nbsp;</th>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t");
if(list != null){
					for(int i = 0; i < list.size(); i++){
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td style=\"text-align:center; width:14%\">");
      out.print(list.get(i).getOrderNum() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td style=\"text-align:center; width:14%\">");
      out.print(list.get(i).getName() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td style=\"text-align:center; width:14%\">");
      out.print(list.get(i).getPrice());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td style=\"text-align:center; width:14%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t");
      out.print(list.get(i).getPurchaseOrderDate().replace("-", "/") );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td style=\"text-align:center; width:14%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t");
if(list.get(i).getPaymentStatus().equals("1")){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t未入金\r\n");
      out.write("\t\t\t\t\t\t\t\t");
}else if(list.get(i).getPaymentStatus().equals("2")){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t入金済み\r\n");
      out.write("\t\t\t\t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td style=\"text-align:center; width:14%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t");
if(list.get(i).getDeliveryStatus().equals("1")){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t未発送\r\n");
      out.write("\t\t\t\t\t\t\t\t");
}else if(list.get(i).getDeliveryStatus().equals("2")){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t発送準備中\r\n");
      out.write("\t\t\t\t\t\t\t\t");
}else if(list.get(i).getDeliveryStatus().equals("3")){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t発送済み\r\n");
      out.write("\t\t\t\t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td style=\"text-align:center; width:14%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"");
      out.print(request.getContextPath() );
      out.write("/orderDetail\">詳細</a>/\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"");
      out.print(request.getContextPath() );
      out.write("/statusUpdate\">更新</a>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t");
}
				} 
      out.write("\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- フッター -->\r\n");
      out.write("\t\t\t");
      out.write("<footer style=\"text-align:left; position:absolute; bottom:100; width:100%\">\r\n");
      out.write("\t<hr style=\"height:3; background-color:#32CD32\"/>\r\n");
      out.write("\t<p style=\"font-color:#00FF00\">Copyright(C)2023 All Right Reserved</p>\r\n");
      out.write("</footer>");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
